### ISSUE TITLE
DCF-77- / GPS-Uhrzeit und Datumsanzeige in der Weboberfläche

### ISSUE THREAD

**Issue by Triton-KS** [alexreinert/HB-RF-ETH#1]
Hallo Alex,
wie angesprochen würde es mich freuen wenn du auf der Weboberfläche folgendes mit aufnehmen könntest:
- Datum-, Uhrzeitanzeige und Sommer oder Winterzeitflak bei DCF-77,
- Datum-, Uhrzeitanzeige, Signalstärke bei GPS

Wie auch geschrieben würde ich keine Umrechnung der Uhrzeit benötigen.
Wenn die Uhrzeit in UTC über DCF-77- oder GPS-Taktquelle auch als (S)NTP Server im Netzwerk zur Verfügung steht,
ist es auch super

Danke

**Comment by alexreinert** [comment]
Die Uhrzeit wird auch per SNTP im Netz bereitgestellt. Da wird UTC verwendet, weil SNTP immer in UTC läuft, die Umrechnung auf eine Zeitzone erfolgt immer erst am Client.
