### ISSUE TITLE
RF-LAN Gateway

### ISSUE THREAD

**Issue by lukicsl** [alexreinert/HB-RF-ETH#24]
After setting the RaspberryMatic (latest version) up to be a RF-LAN Gateway (touch /usr/local/HMLGW) and rebooting the LED turns after being a short time green to red.
I presume this means an error status.
Has the HB-RF-ETH even been tested in such a configuration?

**Comment by alexreinert** [comment]
For RaspberryMatic support, please ask at the RaspberryMatic project, this is neither a HB-RF-ETH hardware nor firmware issue.

**Comment by lukicsl** [comment]
Is there anywhere a description of the LED-color codes?

**Comment by alexreinert** [comment]
The LED is driven by the connected host, so it depends on the software of the host.

**Comment by lukicsl** [comment]
sorry was a misunderstanding, closing
