### ISSUE TITLE
debmatic findet hb-rf-eth nicht

### ISSUE THREAD

**Issue by StefTank** [alexreinert/HB-RF-ETH#28]
Hallo, 
hb-rf-eth ist im netz erreichbar. Firmware wurde auf 1.2.9 gebracht.
debmatic wurde in einer neuen VM (nicht LXC) unter Proxmox installiert. hb-rf-eth wird hier mit der richtigen IP erkannt.
![image](https://user-images.githubusercontent.com/43825115/149820344-ee938cbd-dc8e-4c49-b07d-5853224f9091.png)
Mehrfache Neustarts und wechsel von Debian auf Ubuntu brachte keine Abhilfe.
Ein sudo dpkg-reconfigure hb-rf-eth hilft auch nicht.
![image](https://user-images.githubusercontent.com/43825115/149820807-3ae76c8a-d587-43f1-9455-21c97f19f1fe.png)
Jetzt brauche ich Hilfe....

**Comment by dlmcm87** [comment]
Hallo, das Problem habe ich jetzt auch - nach upgrade debmatic 3.61.7.89 im proxmox container.

Host / Proxmox connected zum HB-RF-ETH. Debmatic im Container hat keine Verbindung mehr ... Gibt schon Erkenntnisse?Workarounds?

**Comment by handy80** [comment]
hier scheint das selbe Problem vorzuliegen. Hatte ein neues Gateway in meinem Netzwerk installiert. PiVCCU3 und RaspberryMatic ausprobiert, aber keine INstallation findet die HB-RF-ETH. Obwohl ich direkt auf die kleine WebOberfläche der HB-RF-ETH draufkomme

**Comment by Schlonzmann** [comment]
Wenn mann eine vollwertige VM unter Proxmox erstellt funktioniert es.
Musste sudo apt install HB-RF-ETH aber nochmals mit sudo apt reinstall hb-rf-eth
Ausführen weil er es beim erstenmal auch nicht gefunden hatte
