### ISSUE TITLE
Reboot über Weboberfläche oder per SSH

### ISSUE THREAD

**Issue by schmupu** [alexreinert/HB-RF-ETH#37]
Ist es möglich über die Weboberfläche oder per SSH einen reboot durchzuführen. Ab und an bleibt bei mir das Modul hängen und ich muss es vom Strom nehmen damit es wieder funktioniert. Das ist immer etwas nervig wenn man im Urlaub, weit weg von zu Hause ist und man nichts tun kann.

**Comment by theexit** [comment]
+1

**Comment by marcprenger** [comment]
+1 (SSH preferred)

**Comment by Huelsi** [comment]
+1
