### ISSUE TITLE
Feature-Request: Zustand des NTP anzeigen

### ISSUE THREAD

**Issue by darkman242** [alexreinert/HB-RF-ETH#6]
Hi, ist es möglich in der Weboberfläche den aktuellen Status (verbunden, aktuelle Zeit) des NTP einzubinden? Ich weiss nicht ob bei den anderen Zeitquellen diese Infos irgendwo angezeigt werden.

**Comment by peter-mul** [comment]
Ja, es wäre 'nice to have' die Quelle/lastupdate und Zeit zu sehen.
