### ISSUE TITLE
Findet kein Physisches Netz

### ISSUE THREAD

**Issue by janner2000** [alexreinert/HB-RF-ETH#7]
Hallo an alle...
Ich habe folgendes Problem. Ich betreibe die HB-RF-ETH per POE Netzteil, dieses wollte ich ab gestern in den Dauerbetrieb nehmen. Funktionierte auch an einer VM-Raspberrymatic wundervoll. Ich habe sie auch gestern auf die neue Firmware 1.29 geupdatet. Jetzt habe ich leider folgendes Problem mit der Platine diese findet auf einmal kein physischer Netz mehr. POE Power startet die Platine auch hoch bis zum grünen Licht auf der Platine. Das Gleiche auch probiert ohne POE sondern mit dem Originalem Netzteil der CCU3 gleiches Problem. Die grüne LED auf dem Netzwerkanschluss flackert beim starten ab und zu schnell dann auch wieder nicht. Reset habe ich auch schon mehrmals ausgeführt keine Änderung. Kann es sein das die Firmware geschrotet ist oder auch wurde???
Nehme ich eine USB Stromversorgung bleiben am Netzwerkmodul die LEDs dunkel.
Kann einer helfen???

Gruß

**Comment by PeXXX** [comment]
Hallo,

ein ähnliches Problem habe ich auch nach dem Flashen der 1.29. Gibt es eine Anleitung zum Flashen via USB? Studio Visual Code & Platformio sind vorhanden, allerdings hört es dann auf bei mir.
Schöne Grüße,
Pekka
