### ISSUE TITLE
NTP-Server funktioniert unter Windows nicht

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [alexreinert/HB-RF-ETH#8]
Hallo,
ich versuche, die NTP-Server-Funktion auf meinen PCs etc. zu nutzen. Unter Linux scheint es problemlos zu funktionieren, den HB-RF-ETH als Zeitserver zu konfigurieren. Unter Windows bekomme ich aber nur folgenden Fehler: "Bei der Synchronisierung mit 192.168.10.88 ist ein Fehler aufgetreten.". Es scheint aber nicht komplett nicht zu funktionieren, mit folgendem Befehl in der commandline bekomme ich eine sinnvolle Ausgabe:
```
>w32tm /stripchart /computer:192.168.10.88
192.168.10.88 wird verfolgt [192.168.10.88:123].
Es ist 27.02.2021 11:02:53.
11:02:53, d:+00.0005303s o:-00.1879851s  [                          *|                           ]
11:02:55, d:+00.0009698s o:-00.1881612s  [                          *|                           ]
11:02:57, d:+00.0007164s o:-00.1881197s  [                          *|                           ]
```
allerdings wird dabei nichts gesetzt. Auch ein `>w32tm /resync` liefert nach einiges Sekunden nur den Fehler
```
Befehl zum erneuten Synchronisieren wird an den lokalen Computer gesendet.
Der Computer wurde nicht synchronisiert, da keine Zeitdaten verfügbar waren.
```

Ist es bekannt, dass die NTP-Server-Funktion in Verbindung mit Windows nicht funktioniert? Falls zur weiteren Analyse noch Wireshark-Protokolle oder sonstige Logs benötigt werden, kann ich diese gerne bereitstellen.

Viele Grüße
Mike

**Comment by peter-mul** [comment]
Ja, windows hat da einige Probleme.

Der NTP Server aber funktioniert:
PS C:\Users\Peter> w32tm /stripchart /computer:HB-RF-ETH-11
Tracking HB-RF-ETH-11 [10.1.0.12:123].
The current time is 09.03.2021 16:41:22.
16:41:22, d:+00.0007390s o:-00.1822448s  [                          *|                           ]
16:41:24, d:+00.0006403s o:-00.1822703s  [                          *|                           ]
16:41:26, d:+00.0014408s o:-00.1826686s  [                          *|                           ]

Die Antwort ist im Wireshark gut sichtbar.
![grafik](https://user-images.githubusercontent.com/80383047/110591308-324f0f00-8179-11eb-8a21-3ac3481272fa.png)

Gruß,
Peter
